Iter24
AndroidReptiloid/monitoring pull request #22
Opened 2023-03-21 17:02 UTC by AndroidReptiloid

2023-03-27 07:42 UTC, bambruysk requested changes
Не реализован GRPC

2023-04-04 20:53 UTC, bambruysk commented
Тесты падают с race detection - где-то гонки.
А где собственно говоря реализация grpc сервера?

2023-04-04 20:56 UTC, bambruysk requested changes
Нужно реализовать grpc не сервере

2023-04-04 20:56 UTC, bambruysk commented on cmd/agent/main.go
> +	grpcClient := proto.NewAgentClient(grpcConn)
Не стоит инжектить соединение - лучше это все убрать в конструктор клиента

2023-04-04 20:56 UTC, bambruysk commented on cmd/agent/main.go
> +		resp, err := httpClient.R().
Не хватает контекста -  чтобы если что-то подвиснет- выйти

2023-04-04 20:56 UTC, bambruysk commented on cmd/agent/main.go
> +		resp, err := grpcClient.AddMetric(context.Background(), &proto.AddMetricRequest{Metrics: &gRPCMetrics})
Контекст использовать с таймаутом здесь нужно

2023-04-20 11:52 UTC, rktkov approved these changes

2023-04-20 11:52 UTC, rktkov commented on cmd/agent/grpcClient.go
> +	"github.com/AndroidReptiloid/monitoring/internal/config"
Не забываем группировать все импорты по блокам

2023-05-02 12:05 UTC, merged